apiVersion: apps/v1
kind: Deployment
metadata:
  name: srini-container
  labels:
    app: srini
spec:
  replicas: 2
  selector:
    matchLabels:
      app: srini
  template:
    metadata:
      labels:
        app: srini
    spec:
      containers:
      - name: srini
        image: nginx:1.14.2
        ports:
        - containerPort: 80
